---
configure_terminal: yes
configure_osx: yes
configure_dotfiles: yes

dotfiles_repo: https://github.com/DemisR/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .aliases
  - .zshrc
  - .gitconfig
  - .gitignore_global
  - .vimrc
  - .vim
  - .osx
  - .functions

homebrew_installed_packages:
  - openssl
  - git
  - tree
  - httpie
  - python
  - python3
  - sqlite
  - nmap
  - ssh-copy-id
  - wget
  - csshx
  - whatmask
  - knock
  - netcat
  - sshuttle
  - awscli
  - terraform
  - vault
  - tmux

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - homebrew/cask-drivers/logitech-options
  - docker
  - dropbox
  - 1password
  - google-chrome
  - handbrake
  - java
  - kap
  - sequel-pro
  - vagrant
  - virtualbox
  - vlc
  - iterm2
  - sourcetree
  - postman
  - atom
  - cyberduck
  - mountain-duck
  - qlcolorcode
  - qlstephen
  - qlmarkdown
  - quicklook-json
  - qlimagesize
  - webpquicklook
  - quicklookase
  - qlvideo
  - suspicious-package
  - spotify
  - postico
  - sequel-pro
  - visual-studio-code
  - go2shell
  - filezilla
  - skype
  - viber
  - telegram

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 425424353 # The Unarchiver
  - 441258766 # Magnet
  - 803453959 # Slack
  - 1295203466 # Microsoft Remote Desktop

#mas_email: ""
#mas_password: ""
